### ISSUE TITLE
Readme errors

### ISSUE THREAD

**Issue by iplayfast** [rapidarchitect/ollama_mesop#1]
To launch your chat run the following from your terminal

`mesop ol_mesop.py`
OR for the streaming version
`mesop ol_mesop.py`

There is no difference. 

pip install mesop.labs returns
RROR: Could not find a version that satisfies the requirement mesop.labs (from versions: none)
ERROR: No matching distribution found for mesop.labs

Also going to the link provided gives an error that it's not been defined (it suggests using /chat)

**Comment by rapidarchitect** [comment]
Sorry typo in the readme, fixed now
